Addition of upstream proxy to resolve slice redirect errors (302 Playstation)
lancachenet/monolithic pull request #156
Opened 2022-10-12 10:02 UTC by VibroAxe

Added new upstream proxy in lancache standard structure.

This resolves #60 by sending all upstream requests via a small 2nd proxy to catch any 302 responses coming from the load balancer "mid slice". Any 302 requests are first followed by the interim proxy and then re-served (slices intact) to the primary lancache block to be cached.

For reasons best known to past me, we seem to be getting some duplicated commits in this PR which are already in main. But all seem to be operational (assuming the CI passes).

2022-10-12 10:05 UTC, mintopia commented
lgtm

2022-10-12 13:32 UTC, MathewBurnett requested changes
mostly ok, some odd indent errors. Also contains
* Moving apt update in docker file
* Cache mem size update
* ipv6 resolver off
* clacks header

2022-10-12 13:32 UTC, MathewBurnett commented on overlay/etc/nginx/nginx.conf
> +
new line for effect

2022-10-12 13:32 UTC, MathewBurnett commented on overlay/etc/nginx/sites-available/20_upstream.conf
> +	# Internal bind on 3128, this should not be externally mapped
odd indent

2022-10-12 13:32 UTC, MathewBurnett commented on overlay/etc/nginx/sites-available/20_upstream.conf
> +	# No access_log tracking as all requests to this instance are already logged through monolithic
odd indent

2022-10-12 13:32 UTC, MathewBurnett commented on overlay/etc/nginx/sites-available/cache.conf.d/root/90_upstream.conf
> +#    proxy_pass http://$host$request_uri;
if this is going, loose the line

2022-10-12 13:32 UTC, MathewBurnett commented on overlay/etc/nginx/sites-available/cache.conf.d/root/90_upstream.conf
> +		# Proxy into the redirect handler
odd indent

2022-10-12 13:32 UTC, MathewBurnett commented on overlay/etc/nginx/sites-available/upstream.conf.d/30_primary_proxy.conf
> +	# Proxy all requests to upstream
odd indent

2022-10-12 13:32 UTC, MathewBurnett commented on overlay/etc/nginx/sites-available/upstream.conf.d/30_primary_proxy.conf
> +		# Catch the errors to process the redirects
odd indent

2022-10-12 13:32 UTC, MathewBurnett commented on overlay/etc/nginx/sites-available/upstream.conf.d/20_tracking.conf
> +	# Header to track if resolved from upstream or 302 redirect
odd indent

2022-10-12 13:32 UTC, MathewBurnett commented on overlay/etc/nginx/sites-available/upstream.conf.d/40_redirect_proxy.conf
> +		# Upstream_http_location contains the Location: redirection from the upstream server
odd indent

2022-10-13 08:00 UTC, VibroAxe commented on Dockerfile
> +RUN	apt-get update							;\
Which other bit?

2022-10-27 08:00 UTC, alexdrean commented
I would love to see this in master so I fixed the indent issues... 
https://github.com/lancachenet/monolithic/compare/playstation...alexdrean:monolithic:playstation

To apply to your local `playstation` branch:
```bash
git remote add alexdrean https://github.com/alexdrean/monolithic.git
git remote update
git checkout origin/playstation
git merge alexdrean/playstation
`


Also, I think Mathew was maybe trying to say that
`RUN apt-get update; install git jq`
should/could go right before
`RUN rm /etc/nginx/sites-enabled/* /etc/nginx/stream-enabled/* ;\`.
That's just a guess, I've been wrong before.

Thank you so much for doing all this debugging work! Fixed my customers' recent issues with PS4/5.

2022-11-12 11:17 UTC, MathewBurnett commented on Dockerfile
> +	mkdir -m 755 -p /tmp/nginx
Can this go in the layer with the other mkdir?

2022-11-12 11:53 UTC, VibroAxe commented on Dockerfile
> +RUN	apt-get update							;\
Moved above ENV to improve flow

2022-11-12 12:01 UTC, MathewBurnett approved these changes

2022-11-12 12:10 UTC, merged